package com.example.basemodule.bean;

import java.io.Serializable;

public class Account implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.AId
     *
     * @mbggenerated
     */
//    @JsonProperty(value = "aid")
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.AName
     *
     * @mbggenerated
     */
//    @JsonProperty(value = "aname")
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ASex
     *
     * @mbggenerated
     */
//    @JsonProperty(value = "asex")
    private String asex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.AAvatar
     *
     * @mbggenerated
     */
//    @JsonProperty(value = "aavatar")
    private String aavatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public Account() {
    }

    public Account(Integer aid, String aname, String asex, String aavatar) {
        this.aid = aid;
        this.aname = aname;
        this.asex = asex;
        this.aavatar = aavatar;
    }

    public Integer getAid() {
        return aid;
    }

    public void setAid(Integer aid) {
        this.aid = aid;
    }

    public String getAname() {
        return aname;
    }

    public void setAname(String aname) {
        this.aname = aname;
    }

    public String getAsex() {
        return asex;
    }

    public void setAsex(String asex) {
        this.asex = asex;
    }

    public String getAavatar() {
        return aavatar;
    }

    public void setAavatar(String aavatar) {
        this.aavatar = aavatar;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", aid=").append(aid);
        sb.append(", aname=").append(aname);
        sb.append(", asex=").append(asex);
        sb.append(", aavatar=").append(aavatar);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}