package com.example.basemodule.bean;

import java.io.Serializable;

public class Buddy implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buddy.BID
     *
     * @mbggenerated
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buddy.UserID
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buddy.BuddyID
     *
     * @mbggenerated
     */
    private Integer buddyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buddy
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public Buddy() {
    }

    public Buddy(Integer bid, Integer userid, Integer buddyid) {
        this.bid = bid;
        this.userid = userid;
        this.buddyid = buddyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buddy.BID
     *
     * @return the value of buddy.BID
     *
     * @mbggenerated
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buddy.BID
     *
     * @param bid the value for buddy.BID
     *
     * @mbggenerated
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buddy.UserID
     *
     * @return the value of buddy.UserID
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buddy.UserID
     *
     * @param userid the value for buddy.UserID
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buddy.BuddyID
     *
     * @return the value of buddy.BuddyID
     *
     * @mbggenerated
     */
    public Integer getBuddyid() {
        return buddyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buddy.BuddyID
     *
     * @param buddyid the value for buddy.BuddyID
     *
     * @mbggenerated
     */
    public void setBuddyid(Integer buddyid) {
        this.buddyid = buddyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buddy
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bid=").append(bid);
        sb.append(", userid=").append(userid);
        sb.append(", buddyid=").append(buddyid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}