package com.example.basemodule.bean;

import java.io.Serializable;

public class Collect implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.ColPID
     *
     * @mbggenerated
     */
    private Integer colpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.ColID
     *
     * @mbggenerated
     */
    private Integer colid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.VID
     *
     * @mbggenerated
     */
    private Integer vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collect
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public Collect() {
    }

    public Collect(Integer colpid, Integer colid, Integer vid) {
        this.colpid = colpid;
        this.colid = colid;
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.ColPID
     *
     * @return the value of collect.ColPID
     *
     * @mbggenerated
     */
    public Integer getColpid() {
        return colpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.ColPID
     *
     * @param colpid the value for collect.ColPID
     *
     * @mbggenerated
     */
    public void setColpid(Integer colpid) {
        this.colpid = colpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.ColID
     *
     * @return the value of collect.ColID
     *
     * @mbggenerated
     */
    public Integer getColid() {
        return colid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.ColID
     *
     * @param colid the value for collect.ColID
     *
     * @mbggenerated
     */
    public void setColid(Integer colid) {
        this.colid = colid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.VID
     *
     * @return the value of collect.VID
     *
     * @mbggenerated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.VID
     *
     * @param vid the value for collect.VID
     *
     * @mbggenerated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", colpid=").append(colpid);
        sb.append(", colid=").append(colid);
        sb.append(", vid=").append(vid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}